### ISSUE TITLE
Installation issue 3.6.12

### ISSUE THREAD

**Issue by NatalieJFU** [Premik/blender_rhubarb_lipsync_ng#19]
### Confirmation

- [X] I have followed the troubleshooting guide.

### Summary

I used it previously but for some reason now its no longer working.
I have unistalled and reinstalled the addon and blender and nothing works, this is the error i get when installing.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\nat_j\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rhubarb_lipsync\__init__.py", line 62, in register
    autoloader.find_classes()
  File "C:\Users\nat_j\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rhubarb_lipsync\blender\auto_load.py", line 58, in find_classes
    self.collect_all_submodules()
  File "C:\Users\nat_j\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rhubarb_lipsync\blender\auto_load.py", line 83, in collect_all_submodules
    self.modules = list(self.iter_submodules(directory, self.root_package_name))
  File "C:\Users\nat_j\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rhubarb_lipsync\blender\auto_load.py", line 87, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\nat_j\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rhubarb_lipsync\blender\capture_panel.py", line 9, in <module>
    from . import capture_operators, rhubarb_operators, sound_operators, ui_utils
  File "C:\Users\nat_j\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rhubarb_lipsync\blender\sound_operators.py", line 9, in <module>
    import aud
ImportError: numpy.core.multiarray failed to import

### Rhubarb Lipsync NG addon version

1.5.2

### Blender Version

3.6.12

### Operating System

windows

**Comment by Premik** [comment]
Thank @NatalieJFU  for reporting the issue with the stack trace.

I tried using a fresh installation of Blender 3.6.13 on Windows 10, but I couldn't reproduce the problem. The crash occurs when the Blender audio library `aud` is imported, and it fails because it can't find something from the numpy library. Strange.

Could you please open the `Scripting` tab and simply type `import aud` into the Python console? It should not display any error:
![image](https://github.com/user-attachments/assets/ebd45b2a-f090-4f3a-9ee0-1c1557138bee)


The next step is to [start Blender with a fresh profile](https://github.com/Premik/blender_rhubarb_lipsync_ng/blob/master/troubleshooting.md#run-blender-with-a-fresh-profile-factory-settings):

Open `cmd`, and then enter the following commands:

```cmd
cd "C:\Program Files\Blender Foundation\Blender 3.16\bin"
set BLENDER_USER_RESOURCES=%TEMP%
blender --debug
```

And try to install the plugin into the fresh temp profile.

**Comment by NatalieJFU** [comment]
So I tried the import aud and this was my error
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\startup\bl_operators\console.py", line 39, in execute
    return execute(context, self.interactive)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\console_python.py", line 150, in execute
    is_multiline = console.push(line_exec)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\code.py", line 258, in push
    more = self.runsource(source, self.filename)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import

As another note, I have even done a fresh reset no plugins etc and it is still displaying the original error not the above code.

**Comment by NatalieJFU** [comment]
Update

Asked a former programmer for some assistance and managed to fix the issue.
Seems the Numpy version was on 2.1.1 or they seem to think that i may have installed blender 32-bit.

First used this code:
cd C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\bin

This was where the python.exe was installed then typed in : python.exe -m pip install --upgrade numpy
This made it unistall 2.1.1 and install numpy 1.23.5 which when installing the addon enabled with no issues.

![image](https://github.com/user-attachments/assets/81340d87-49cd-4d85-9297-5178e1e4c251)

**Comment by Premik** [comment]
Glad you managed to fix that. 

What might have also happened is that some extension installed additional packages using pip into Blender's site-packages which also updated NumPy to v2.
