### ISSUE TITLE
Blender 3.6 error - Plugin failed to register on Mac

### ISSUE THREAD

**Issue by impactcolor** [Premik/blender_rhubarb_lipsync_ng#9]
Thank you so much for taking over this project.
When attempting to install on a Mac.
1.0.1 or 1.0.2

`Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/{user}/Library/Application Support/Blender/3.6/scripts/addons/rhubarb_lipsync/__init__.py", line 34, in <module>
    rhubarb_lipsync.blender.auto_load.init(__file__)
AttributeError: partially initialized module 'rhubarb_lipsync' has no attribute 'blender' (most likely due to a circular import)
`
1.0.3 also gives an error regarding numpy installation

**Comment by Premik** [comment]
Thanks for trying this plugin on Mac. This really valuable. (My hope was Github-actions could cover all the platforms but I couldn't find the blender-as-module conda package for Mac).

Anyway the error you've attached is a generic exception meaning the plugin failed to register. There should be some more errors reported earlier before this one, but it might not be easy to find them as they. They might not be in the Blender scripting console. What might help is to [run Blender from terminal](https://blender.stackexchange.com/questions/102860/how-to-open-system-console-to-get-output-from-blender-on-mac-os-10) Would you be able to try to locate the original error?

>1.0.3 also gives an error regarding numpy installation.

That is strange. The plugin doesn't need numpy as far as I know.

**Comment by impactcolor** [comment]
Hi thanks for tagging in on this.  Yes the full error for 1.0.0 on Blender 3.6 is this:
```
Traceback (most recent call last):
  File "/Volumes/Megatron/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/Ohms/Library/Application Support/Blender/3.6/scripts/addons/rhubarb_lipsync/__init__.py", line 34, in <module>
    rhubarb_lipsync.blender.auto_load.init(__file__)
AttributeError: partially initialized module 'rhubarb_lipsync' has no attribute 'blender' (most likely due to a circular import)


```
I'll run it from terminal and tag in with you.

**Comment by Premik** [comment]
Thanks for trying this out. Still that additional message is not useful and I was not able to reproduce the error. I tried:

- Blender `3.6.7` on `Linux`. Plugin versions `1.0.1`, `1.0.2`, `1.0.3`
- Blender `3.4.1` on `Mac 10.13` v `1.0.3` (can't run newer Blender on that os)

All works (to the point where the plugin registers).


I've used a simple script which grabs the plugin from github and runs a smoke test. Can you try the following please:

```sh
cd /Applications/Blender.app/Contents/MacOS
curl https://raw.githubusercontent.com/Premik/blender_rhubarb_lipsync_ng/master/scripts/adhoc-install.py -o adhoc-install.py
XDG_CONFIG_HOME=/tmp/blenderTemp ./Blender --background --python adhoc-install.py
```

This would download the `1.0.3` version and run Blender changing the user config folder temporally to `/tmp` making it fresh.
If all works you should see 2x`{'FINISHED}'` printed out to terminal:

![image](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/842962/1d7c2264-4392-459d-8e08-b38be732fc93)

**Comment by Premik** [comment]
Hi @impactcolor ,
If you are still around and provided you are still facing the same issue, [the latest version](https://github.com/Premik/blender_rhubarb_lipsync_ng/releases) has somehow improved logging and few bugs fixed..

And there is [Troubleshooting guide](https://github.com/Premik/blender_rhubarb_lipsync_ng/blob/master/troubleshooting.md) with additional hints.

**Comment by Premik** [comment]
Closing as not reproducible.
